spring:
  profile: 'local'
  application:
    name: 'tax-calc-app'
  data:
    mongodb:
      database: taxcalc
server:
  port: 8080

jwt:
  secret.key: 'nnmmnnmm'

email:
  service:
    enabled: true
    host: localhost
    scheme: http
    port: 8040
    endpoints:
      send-mail: /email/send
